spring.application.name=investigacion-spring-boot

spring.datasource.url=jdbc:h2:mem:authdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.h2.console.enabled=true

file-storage.base-url=http://localhost:555
file-storage.upload-url-path=/files/upload-url
file-storage.download-url-path=/files/{fileId}
